---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: heading
  label: Entries
- type: directory
  path: src/posts/content
  label: Posts
  create: all
  match: "**/*.md"
  new_doc_ext: md
  templates:
  - posts
- type: directory
  path: src/echos/content
  label: Echos
  create: all
  match: "**/*.md"
  new_doc_ext: md
  templates:
  - echos
- type: directory
  path: src/notes/content
  label: Notes
  create: all
  match: "**/*.md"
  new_doc_ext: md
  templates:
  - notes
- type: heading
  label: Pages
- type: directory
  path: src/home/content
  label: Pages
  create: all
  match: "**/*.md"
  new_doc_ext: md
  templates:
  - pages
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_VERSION=0.67.1
  preview_output_directory: dist
  install_dependencies_command: yarn install
  preview_docker_image: forestryio/hugo:node10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn run forestry
