  website: bookmarks 
  title: "ブックマーク"
  description: "『輝かしい青春』なんて失かった方の<br>『にゃるら』のブックマーク。<br>本体は Pinboard にある"

# Title
title: "カラクリスタ・ブックマーク"

# Permalink
baseURL: "https://the.kalaclista.com/bookmarks"
disableKinds:
  - taxonomyTerm
  - sitemap
  - robotosTXT
  - "404" 

outputs:
  home:
    - HTML
    - Atom
    - RSS
    - JSONFeed
    - JSONIndex
  section:
    - HTML
  page: []
