  website: bookmarks 

# Title
title: "カラクリスタ・ブックマーク"

# Permalink
baseURL: "https://the.kalaclista.com/bookmarks"
disableKinds:
  - taxonomyTerm
  - sitemap
  - robotosTXT
  - "404" 

outputs:
  home:
    - HTML
    - Atom
    - RSS
    - JSONFeed
    - JSONIndex
  section:
    - HTML
  page: []
