  website: echos 

# Title
title: "カラクリスタ・エコーズ"

# Permalink
baseURL: "https://the.kalaclista.com/echos"
disableKinds:
  - taxonomyTerm
  - sitemap
  - robotosTXT
  - "404" 

permalinks:
  echos: /:year/:month/:day/:slug

outputs:
  home:
    - HTML
    - Atom
    - RSS
    - JSONFeed
    - JSONIndex
  section:
    - HTML
  page:
    - HTML
