# metadata
metaDataForamt: yaml

# language
languageCode: ja
defaultLanguageCode: ja
hasCJKLanguage: true

# URL
disablePathToLower: true
taxonomies:
  tag: "tags"

paginate: 15
paginatePath: "pages"

# format
pygmentsCodeFences: true
pygmentsUseClasses: true

blackfriday:
  smartypants: false
  extensionsmark:
    - noIntraEmphasis

# output
mediaTypes:
  application/atom+xml:
    suffixes:
      - xml

outputFormats:
  JSONFeed:
    mediaType: application/json
    baseName: jsonfeed
    isPlainText: true
  JSONIndex:
    mediaType: application/json
    baseName: jsonindex
    isPlainText: true
  Atom:
    mediaType: application/atom+xml
    baseName: atom
    isPainText: false

layoutDir: ../../templates
assetDir: ../../assets

params:
  adsense:
    top: |-
      <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
      <ins class="adsbygoogle"
           style="display:block"
           data-ad-format="fluid"
           data-ad-layout-key="-fv-j+1z-5r+9a"
           data-ad-client="ca-pub-1273544194033160"
           data-ad-slot="5004342069"></ins>
      <script>
           (adsbygoogle = window.adsbygoogle || []).push({});
      </script>
    bottom: |-
      <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
      <ins class="adsbygoogle"
           style="display:block"
           data-ad-format="fluid"
           data-ad-layout-key="-fv-j+1z-5r+9a"
           data-ad-client="ca-pub-1273544194033160"
           data-ad-slot="7658425566"></ins>
      <script>
           (adsbygoogle = window.adsbygoogle || []).push({});
      </script>


  analysis: |-
    <!-- Fathom - simple website analytics - https://github.com/usefathom/fathom -->
    <script>
    (function(f, a, t, h, o, m){
      a[h]=a[h]||function(){
        (a[h].q=a[h].q||[]).push(arguments)
      };
      o=f.createElement('script'),
      m=f.getElementsByTagName('script')[0];
      o.async=1; o.src=t; o.id='fathom-script';
      m.parentNode.insertBefore(o,m)
    })(document, window, '//analysis.nyarla.net/tracker.js', 'fathom');
    fathom('set', 'siteId', 'WIXUH');
    fathom('trackPageview');
    </script>
    <!-- / Fathom -->

  labels:
    home: 入口
    posts: 記事
    echos: 雑文
    notes: 覚書
    bookmarks: 参照
    search: 検索
    archives: 記録

  title:
    posts: "ブログ"
    echos: "エコーズ"
    notes: "ノート"
    bookmarks: "ブックマーク"
    search: "サーチ"
    archives: "アーカイブ"
    notfound: "イズ・ノット・ファウンド"

  message:
    default: "[※なおライターだったり VTuber な<br>『にゃるら』さんとは別の人間です](/notes/nyarla-is-not-nyalra/)。**人違い注意**"
    search: "とは言え、検索だけでは<br>見付からない記事なども有るかもしれません"
    notfound: "記事が行方不明になっててすみません。<br>検索するともしかすると見付かるかもです"

  description:
    home: "『輝かしい青春』なんて失かった方の<br>『にゃるら』の個人 Webサイトです"
    posts: "『輝かしい青春』なんて失かった方の<br>『にゃるら』のブログ。<br>過去の遺物が色々混ざってます"
    echos: "『輝かしい青春』なんて失かった方の<br>『にゃるら』のぼやき。<br>あるいはチラシの裏"
    notes: "『輝かしい青春』なんて失かった方の<br>『にゃるら』のノート。<br>いわゆるまとめ系"
    bookmarks: "『輝かしい青春』なんて失かった方の<br>『にゃるら』のブックマーク。<br>ここが本体です"
    search: "『輝かしい青春』なんて失かった方の<br>『にゃるら』の個人 Webサイトを検索します"
    archives: "『輝かしい青春』なんて失かった方の<br>『にゃるら』の過去ログ。<br>色々と歴史がある"
    notfound: "いわゆる 404 Not Found 。<br>ページが見付かりません"

  breadcrumb: {}

  feed:
    home: "カラクリスタの %s Feed"
    search: "カラクリスタの %s Feed"
    archives: "カラクリスタの %s Feed"
    notfound: "カラクリスタの %s Feed"
    posts: "カラクリスタ・ブログの %s Feed"
    echos: "カラクリスタ・エコーズの %s Feed"
    notes: "カラクリスタ・ノートの %s Feed"
    bookmarks: "カラクリスタ・ブックマークの %s Feed"

  tag:
    posts: "%s と言うタグの付いた記事"
    bookmarks: "%s と言うタグの付いたブックマーク"

  helps:
    - label: "運営者"
      items:
        - title: "プロフィール"
          link: "/nyarla/"
        - title: "カラクリスタについて"
          link: "/about/"
    - label: "各情報"
      items:
        - title: "プライバシーポリシー"
          link: "/privacy/"
        - title: "ライセンスなど"
          link: "/licenses/"
    - label: "その他"
      items:
        - title: "GitHub"
          link: "https://github.com/nyarla/"
        - title: "Gitlab"
          link: "https://gitlab.com/nyarla/"
        - title: "Twitter"
          link: "https://twitter.com/kalaclista"
