  website: notes 
  title: "ノート"
  description: "『輝かしい青春』なんて失かった方の<br>『にゃるら』のノート。<br>いわゆるまとめ系"

# Title
title: "カラクリスタ・ノート"

# Permalink
baseURL: "https://the.kalaclista.com/notes"
disableKinds:
  - taxonomyTerm
  - taxonomy
  - sitemap
  - robotosTXT
  - "404" 

permalinks:
  notes: /:slug

outputs:
  home:
    - HTML
    - Atom
    - RSS
    - JSONFeed
    - JSONIndex
  section:
    - HTML
  page:
    - HTML
