  website: posts 
  title: "ブログ"
  description: "『輝かしい青春』なんて失かった方の<br>『にゃるら』のブログ。<br>過去の遺物が色々混ざってます。"

# Title
title: "カラクリスタ・ブログ"

# Permalink
baseURL: "https://the.kalaclista.com/posts"
disableKinds:
  - taxonomyTerm
  - sitemap
  - robotosTXT
  - "404" 

permalinks:
  posts: /:year/:month/:day/:slug

outputs:
  home:
    - HTML
    - Atom
    - RSS
    - JSONFeed
    - JSONIndex
  section:
    - HTML
  page:
    - HTML
